{{- if .Values.autoDeploy }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-upgrade-job"
  labels:
    component: upgrade-job
    {{- include "dast.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        component: upgrade-job
        {{- include "dast.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: upgrade-job
          image: "{{ .Values.images.upgradeJob.repository }}:{{ .Values.images.upgradeJob.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.upgradeJob.pullPolicy }}
          args:
            - "configureEnvironment"
            - "--mode"
            - "autodeploy"
            - "--settingsFile"
            - 'c:\settings\appsettings.yaml'
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            {{- with .Values.upgradeJob.additionalEnvironment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: appsettings
              mountPath: 'c:\settings\'
      volumes:
        - name: appsettings
          secret:
            secretName: {{ include "secret.name" . }}
      nodeSelector:
      {{- with .Values.upgradeJob.nodeSelector }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.upgradeJob.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.upgradeJob.tolerations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 0
{{- end }}
