{{- if and .Values.controller.enabled .Values.controller.trustedCertificates }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "scancentral-sast-controller.fullname" . }}
  labels:
    {{- include "scancentral-sast.labels" . | nindent 4 }}
data:
  {{- range $i, $cert := .Values.controller.trustedCertificates }}
  {{ printf "trusted-cert-%d.pem" $i }}: {{ $cert | quote }}
  {{- end }}
{{- end }}
