{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.name" . }}
  labels:
    component: secret
    {{- include "lim.labels" . | nindent 4 }}
type: Opaque
data:
  lim-admin-password: {{ .Values.adminPassword | b64enc | quote }}
{{- end }}